channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =2.1.1
  - pyyaml =6.0.1
  - jinja2 =3.1.2
  - paramiko =3.3.1
  - tqdm =4.66.1
  - pympipool =0.7.1
  - cloudpickle =2.2.1
