channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =2.0.3
  - pyyaml =6.0
  - jinja2 =3.1.2
  - paramiko =3.3.1
  - tqdm =4.65.0
  - pympipool =0.6.2
  - cloudpickle =2.2.1
