channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coverage
  - pandas =2.1.3
  - pyyaml =6.0.1
  - jinja2 =3.1.2
  - paramiko =3.3.1
  - tqdm =4.66.1
  - pympipool =0.7.2
  - cloudpickle =3.0.0
